# Sample .travis.yml for R projects

language: r
cache:
  - packages
warnings_are_errors: false
sudo: required

#addons:
#  postgresql: "9.6"

# before_install:
#  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
#  - sudo apt-get -qq update
#  - sudo apt-get install -y libgdal-dev libproj-dev
#  - export DISPLAY=:99.0
#  - sh -e /etc/init.d/xvfb start

 # - sudo apt-get --yes --force-yes update -qq
 # - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev
 # - sudo apt-get --yes install libjson-c-dev postgresql-server-dev-9.6
 # - wget http://download.osgeo.org/postgis/source/postgis-2.3.2.tar.gz
 # - (mv postgis* /tmp; cd /tmp; tar xzf postgis-2.3.2.tar.gz)
 #  - (cd /tmp/postgis-2.3.2 ; ./configure; make; sudo make install)
 # - sudo ldconfig
 # - export DISPLAY=:99.0
 #  - sh -e /etc/init.d/xvfb start

matrix:
  include:
    - os: linux
      dist: trusty
      env:
      global:
      - R_BUILD_ARGS="--no-multiarch --with-keep.source "
      - R_CHECK_ARGS="--no-manual --timings --no-tests"
      - R_CHECK_TIMINGS_="0"
    #  - BOOTSTRAP_LATEX="1"
      addons:
        apt:
          packages:
            - libcairo2-dev
            - libatk1.0-dev
            - libpango1.0-dev
            - libgtk2.0-dev
            - libglib2.0-dev
            - libcurl4-openssl-dev
            - libgdal-dev
            - libproj-dev
            - units
            - libudunits2-dev
      r_binary_packages:
        - cairoDevice
        - RGtk2

r_packages:
  - covr
  - sf

after_success:
#  - Rscript -e 'covr::codecov()'
#  - dropdb postgis
#  - createdb postgis
#  - psql -d postgis -c "CREATE EXTENSION postgis;"
#  - psql -d postgis -c "GRANT CREATE ON DATABASE postgis TO travis"
